HETEROGENEOUS = True
LOCAL_WORKLOAD_PERIOD = 20
EXTRA_AGENT = 1
OBSERVER_WORKLOAD = True
NON_SHANNON_DATA_RATE = 150*(2**10)*(2**10)
ACTION_DIM = 2
WORKER_NUMBER_MAX = 100
MAX_LOCAL_TASK_DELAY = 1
MIN_LOCAL_TASK_DELAY = 0.1
MAX_WORKER_POWER = 20
MIN_WORKER_POWER = 10
SOB_DIM = 102
DYNAMIC_PRICE = False
if DYNAMIC_PRICE:
    LOCAL_OBS_DIM = 8
else:
    LOCAL_OBS_DIM = 7
MASTER_PRICE = 0
UNAVAILABLE_PRICE = 10
TIME_SLOT = 100
STATE_RATIO = 1
PR_MAX = 0.95
PR_MIN = 0
POISSON = False
CONTINUE_PROBABILITY = 0.8